TILE_MAP_WIDTH, TILE_MAP_HEIGHT = 10,9
GRAVITY = .75
PLAYER_ATTACK_SPRITESHEET_SIZE = 8
PLAYER_DEATH_SPRITESHEET_SIZE = 5
PLAYER_IDLE_SPRITESHEET_SIZE = 8
PLAYER_MOVE_SPRITESHEET_SIZE = 8
PLAYER_TAKEN_DAMAGE_SPRITESHEET_SIZE = 0
PLAYER_ATTACK = 2
PLAYER_RUN = 0
PLAYER_IDLE = 1
PLAYER_TAKEN_DAMAGE = 3
PLAYER_DEATH = 4
FLOOR_ROW = 8
ANIMATION_COOLDOWN = 100
TILE_CORNER_NUMBER = 4
GAME_LEVEL = "new_level_test.csv"


PLAYER_SPRITESHEET_SIZES = [
    PLAYER_MOVE_SPRITESHEET_SIZE,
    PLAYER_IDLE_SPRITESHEET_SIZE,
    PLAYER_ATTACK_SPRITESHEET_SIZE,
    PLAYER_TAKEN_DAMAGE_SPRITESHEET_SIZE,
    PLAYER_DEATH_SPRITESHEET_SIZE]
